apiVersion: v1
kind: Namespace
metadata:
  name: e2e-staging
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1.0.102
  name: canary-demo
  namespace: e2e-staging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: canary-demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1.0.102
  name: canary-demo-preview
  namespace: e2e-staging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: canary-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    version: v1.0.102
  labels:
    db-schema: v1.4
    environment: staging
  name: canary-demo
  namespace: e2e-staging
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
      - setWeight: 20
      - pause:
          duration: 5
      - setWeight: 80
      - pause:
          duration: 5
  template:
    metadata:
      annotations:
        version: v1.0.102
      labels:
        app: canary-demo
        environment: staging
    spec:
      containers:
      - image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        name: canary-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
