apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: staging
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: staging
